// <auto-generated />
using Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20170918171942_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("Message")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("Name")
                        .HasColumnName("NOME");

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("TELEFONE");

                    b.Property<string>("Subject")
                        .HasColumnName("SUBJECT");

                    b.HasKey("Id");

                    b.ToTable("TB_CONTACT");
                });
#pragma warning restore 612, 618
        }
    }
}
